### ISSUE TITLE
Ability to export flow as image

### ISSUE THREAD

**Issue by tugh** [ertugrulcetin/re-frame-flow#5]
I think it would be nice to export the flow as an image for future uses.

I've found that [exporting the flow as SVG would be pretty complex](https://github.com/wbkd/react-flow/discussions/1139) but it should be easier to export as JPG/PNG.

**Comment by ertugrulcetin** [comment]
I can't think of any use case right now, is it something you need at the moment?

**Comment by tugh** [comment]
Yes, I want to capture different flows and export them to use in documentation. I can create a PR when I get time if that's OK?

**Comment by ertugrulcetin** [comment]
Sure, I'd be happy to accept PRs!

**Comment by ertugrulcetin** [comment]
@tugh Any updates?

**Comment by tugh** [comment]
> @tugh Any updates?

nope
